name: family_tree
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  graphql_flutter: ^5.1.2
  graphview: ^1.1.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  jwt_decode: ^0.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  permission_handler: ^11.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  printing: ^5.12.0
  image: ^4.5.4
  pdf: ^3.10.4
  flutter_force_directed_graph: ^1.0.7
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # ✅ Add this line

flutter:
  uses-material-design: true
  assets:
    - assets/icons/family_tree.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/family_tree.png"

